### create an order
POST http://localhost:8080/orders/create
Content-Type: application/json

{
  "userId": 103,
  "productId": 33,
  "amount": 4000
}

### create an order
POST http://localhost:8080/orders/create
Content-Type: application/json

{
  "userId": 103,
  "productId": 12,
  "amount": 800
}

### get orders
GET http://localhost:8080/orders
Content-Type: application/json

###



